### ISSUE TITLE
Anyone interested in finishing this project

### ISSUE THREAD

**Issue by KelvinJones** [nextcloud/files_frommail#14]
I'm looking for someone interested in finishing this. I'm not a programmer.  All the enhancements look good and I have a specific request for this (or an app like it on Nextcloud).  

BASIC REQUIREMENT
We want to be able to send an email with an attachment to any number of different folders based on the "email address" of the folder and later be able to browse the folder on the Nextcloud app and see the files from email.

I need to discuss scope and thereafter please quote and I'll try to raise funding. Happy to make the product available free to the community thereafter.

Apologies if this is the wrong place to ask this and if so please point me in the right direction.

Happy to share personal email details and chat offline too.

**Comment by KelvinJones** [comment]
We want to send an email to our Nextcloud server.

A folder (or any folder(s) we choose) on the server should be "email enabled" to receive an email with an attachment From: email addresses that we specify (for security).

The email should go into the folder based on the email address we send To:.

Only emails with attachments will be accepted.

We should be able to open the folder and see all the email attachments (the files) that have been emailed to that folder.

Let me know if you need any further clarity.

**Comment by jospoortvliet** [comment]
We'd be happy to help with this, @KelvinJones - but best go through the proper channels, this is for contributor/developer discussion, not enterprise feature requests...

Please email sales@nextcloud.com to get this started. Thanks!

**Comment by daita** [comment]
From the author point of view, this is really out of the scope of the app. This app is supposed to be small and just bounce mail from a specific mail address and create files on Nextcloud. 

What you are asking is an app that extract attachment from an existing/used mail address. This is more something that should be implemented to the Mail app.

**Comment by KelvinJones** [comment]
@jospoortvliet , we are actually looking to have this dev'd for the community.  We are not interested in Enterprise at this time. Just looking for a dev to help us achieve the above.  Happy to elsewhere if this is still the wrong place to look for a dev for this.

**Comment by KelvinJones** [comment]
@daita , I thought what we wanted might be outside the scope of this app. Just trying to find the starting place to commission such an app and turn it over to the community.  Suggestions?

**Comment by daita** [comment]
You should ask on https://help.nextcloud.com/ if you're looking for a developer that would implement this into the Mail app.
