### ISSUE TITLE
How to install!!??

### ISSUE THREAD

**Issue by dylandap** [nextcloud/files_frommail#31]
I installed mailparse and created a new user in nextcloud and filled in the NextcloudMailCatcher.php the necessary config

$config = [
  'nextcloud' => 'https://cloud.example.net/',
  'username'  => 'frommail',
  'password'  => 'Ledxc-jRFiR-wBMXD-jyyjt-Y87CZ',
  'debug'     => false
];

but i still get the following error with the 

php -f ./NextcloudMailCatcher.php test

error:
testing!

Error: password have to be a generated token
Generate a token on the webclient: Settings / Security / Devices & session

How does one install this app in a working state?

**Comment by daita** [comment]
README should be enough
