### ISSUE TITLE
Not configurable on a shared server

### ISSUE THREAD

**Issue by janhsh** [nextcloud/files_frommail#32]
Not configurable on a shared server
A configuration interface is needed

**Comment by jobenvil** [comment]
Having the same issue using 1blu shared hoster.

**Comment by janhsh** [comment]
The problem is: on a shared server, access to the nextcloud configuration file is not possible.
As a result, it is not possible to optimize the configuration or install plugins that require adding lines to the configuration file, this is not possible. (no FTP access on the server and no direct access to the DB).

During the last update, I saw that it was necessary to launch SQL scripts, but as we are on a shared server, direct access to the DB is not possible.

It would take an interface in the admin part of nextcloud to be able to make these modifications

**Comment by daita** [comment]
next release for nc18 will add a way to create/remove mailbox from the admin settings
