### ISSUE TITLE
Does not escape/stip slashes in email address

### ISSUE THREAD

**Issue by derobert** [nextcloud/files_frommail#33]
Email addresses can contain forward-slash, and any number of other characters you don't expect. For example, this is a valid email From: line:

    From: "Some Name" <"some/name"@example.com>

See https://tools.ietf.org/html/rfc5321#section-4.1.2 for the specification. As it warns, "within a quoted string, any ASCII graphic or space is permitted without blackslash-quoting except double-quote and the backslash itself." And a local part (the bit before the `@`) is allowed to be a quoted string.

files_frommail creates unexpected levels of subdirectories when handling these. This doesn't seem to be a security issue (at least on Unix) since `/../` appears to cause file creation to fail. (I don't know about Windows, e.g., if sync'd by the desktop app, which has more special names).

I would suggest that From: email address be sanitized by removing all characters outside of `[-._+@a-zA-Z0-9]` before use.

**Comment by daita** [comment]
should be fixed in next release
