### ISSUE TITLE
Nextcloud 18 support?

### ISSUE THREAD

**Issue by wizdude** [nextcloud/files_frommail#34]
greetings,

i just wanted to check in and find out what your plans were in terms of support for Nextcloud 18.

cheers, wizdude

**Comment by cageyv** [comment]
+1
Waiting for 18.* support

**Comment by e-alfred** [comment]
Nextcloud 18.0.1 is already out, @daita can you create a new release for it? This would be awesome!

**Comment by daita** [comment]
incoming release
