### ISSUE TITLE
Readme (Installation instructions) are very bad

### ISSUE THREAD

**Issue by ExaconAT** [nextcloud/files_frommail#5]
Please recreate the instructions. It's definately not clear what is meant eg ./occ - doesnt even work (sudo -u www-user php occ ...)

Thx

**Comment by daita** [comment]
do not hesitate to fill a pull request

**Comment by ExaconAT** [comment]
Sorry how to open a pulll request?

**Comment by christianlupus** [comment]
> Sorry how to open a pulll request?

You should fork the repository, make your changes and then make a pull request on the github page. See [this page from hithub help](https://help.github.com/articles/proposing-changes-to-your-work-with-pull-requests/) for more information.
