### ISSUE TITLE
Folder names and many mailboxes

### ISSUE THREAD

**Issue by ymolinet** [nextcloud/files_frommail#6]
Hi,

is it possible to have many mailboxes configured in your app ? and  specify how to store attachement ?
Example 
-> test1@example.com store files in FOLDER > MyFolder1 > ReceivedDate
-> test2@example.com store files in FOLDER > MyFolderA > Folder B > 

Thanks,
Yannick

**Comment by daita** [comment]
no, sorry. I am trying to keep the app simple

**Comment by daita** [comment]
Note that you can still have multiple mailboxes !
